### ISSUE TITLE
Am I able to request sdxl 1.0 webui, or can we use a sdxl model/checkpoint providing our own model?

### ISSUE THREAD

**Issue by Irohika** [NUROISEA/anime-webui-colab#41]
Hello I'd like to know if it's possible to install SDXL 1.0, or if there's any other colab that uses the sdxl because I want to use Animagine XL 3.0 model. I don't know if it works if I provide my own model, prob not

**Comment by NUROISEA** [comment]
Yes you can use your own models by using [this colab (PYOM)](https://github.com/NUROISEA/anime-webui-colab?tab=readme-ov-file#-provide-your-own-models-pyom-) ([direct colab link](https://colab.research.google.com/github/NUROISEA/anime-webui-colab/blob/main/notebooks/provide_your_own_models.ipynb)) just use the latest version of the web UI

Since this repository is on its "maintenance phase" meaning no major changes (or new notebooks in this case) I don't feel like adding a new notebook unless the demand is there (or if I feel like it lol)

**Comment by NUROISEA** [comment]
Quick update: I might be adding a notebook based on this model! It looks quite nice!

Probably I'm going to do this in a week or two.... probably

<details><summary>A test generation of my "mascot"/OC/whatever (large image)</summary>

```
1girl, blonde hair, blue eyes, short hair, wavy hair, hair ribbon, blue ribbon, detached sleeves, blue dress, portrait, smile

masterpiece, best quality, very aesthetic, absurdres

Negative prompt: nsfw, lowres, (bad), text, error, fewer, extra, missing, worst quality, jpeg artifacts, low quality, watermark, unfinished, displeasing, oldest, early, chromatic aberration, signature, extra digits, artistic error, username, scan, [abstract]
Steps: 28, Sampler: Euler a, CFG scale: 7, Seed: 3489155775, Size: 768x1344, Model: animagine-xl-3.1, Version: v1.8.0
```

![00024-3489155775](https://github.com/NUROISEA/anime-webui-colab/assets/120075289/a7d92812-9431-49fa-8ec0-380df46596a6)

</details>

**Comment by Irohika** [comment]
Let's gooooooooooooooooooooooooooooooooooooo
I loved the image 

btw that size 768x1344 was with the upscale activated?

**Comment by NUROISEA** [comment]
Haven't used any upscaling, and it takes 1 step / second to generate.

**Comment by NUROISEA** [comment]
Added!

https://colab.research.google.com/github/NUROISEA/anime-webui-colab/blob/main/notebooks/animagine-xl.ipynb
